package cn.xinxing.model;

public class AuthUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.userid
     *
     * @mbggenerated Sun Mar 29 15:48:16 CST 2015
     */
    private Integer userid;
    public Integer getMobile() {
		return mobile;
	}

	public void setMobile(Integer mobile) {
		this.mobile = mobile;
	}

	private Integer mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.username
     *
     * @mbggenerated Sun Mar 29 15:48:16 CST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.password
     *
     * @mbggenerated Sun Mar 29 15:48:16 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.gender
     *
     * @mbggenerated Sun Mar 29 15:48:16 CST 2015
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.email
     *
     * @mbggenerated Sun Mar 29 15:48:16 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.is_outperson
     *
     * @mbggenerated Sun Mar 29 15:48:16 CST 2015
     */
    private Integer isOutperson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.userid
     *
     * @return the value of auth_user.userid
     *
     * @mbggenerated Sun Mar 29 15:48:16 CST 2015
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.userid
     *
     * @param userid the value for auth_user.userid
     *
     * @mbggenerated Sun Mar 29 15:48:16 CST 2015
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.username
     *
     * @return the value of auth_user.username
     *
     * @mbggenerated Sun Mar 29 15:48:16 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.username
     *
     * @param username the value for auth_user.username
     *
     * @mbggenerated Sun Mar 29 15:48:16 CST 2015
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.password
     *
     * @return the value of auth_user.password
     *
     * @mbggenerated Sun Mar 29 15:48:16 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.password
     *
     * @param password the value for auth_user.password
     *
     * @mbggenerated Sun Mar 29 15:48:16 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.gender
     *
     * @return the value of auth_user.gender
     *
     * @mbggenerated Sun Mar 29 15:48:16 CST 2015
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.gender
     *
     * @param gender the value for auth_user.gender
     *
     * @mbggenerated Sun Mar 29 15:48:16 CST 2015
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.email
     *
     * @return the value of auth_user.email
     *
     * @mbggenerated Sun Mar 29 15:48:16 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.email
     *
     * @param email the value for auth_user.email
     *
     * @mbggenerated Sun Mar 29 15:48:16 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.is_outperson
     *
     * @return the value of auth_user.is_outperson
     *
     * @mbggenerated Sun Mar 29 15:48:16 CST 2015
     */
    public Integer getIsOutperson() {
        return isOutperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.is_outperson
     *
     * @param isOutperson the value for auth_user.is_outperson
     *
     * @mbggenerated Sun Mar 29 15:48:16 CST 2015
     */
    public void setIsOutperson(Integer isOutperson) {
        this.isOutperson = isOutperson;
    }
}